services:
  preventech:
    image: preventech
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db: 
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Preventech;Username=preventech;Password=1234
    command: dotnet Preventech.Server.dll

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: Preventech
      POSTGRES_USER: preventech
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U preventech -d Preventech"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    
volumes:
  pgdata: {}
