// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Preventech.Core.DatabaseContexts;

#nullable disable

namespace Preventech.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250916135410_NomeMigracao")]
    partial class NomeMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Preventech.Core.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LocalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Patrimonio")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("Preventech.Core.Models.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Andar")
                        .HasColumnType("integer");

                    b.Property<int>("Campus")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("Predio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Localizacao");
                });

            modelBuilder.Entity("Preventech.Core.Models.Preditiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Frequencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReferenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferenteId");

                    b.ToTable("Preditiva");
                });

            modelBuilder.Entity("Preventech.Core.Models.Preventiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoReferente")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("Frequencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReferenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferenteId");

                    b.ToTable("Preventiva");
                });

            modelBuilder.Entity("Preventech.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Preventech.Core.Models.Equipamento", b =>
                {
                    b.HasOne("Preventech.Core.Models.Localizacao", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("Preventech.Core.Models.Preditiva", b =>
                {
                    b.HasOne("Preventech.Core.Models.Equipamento", "Referente")
                        .WithMany("ManutPreditiva")
                        .HasForeignKey("ReferenteId");

                    b.Navigation("Referente");
                });

            modelBuilder.Entity("Preventech.Core.Models.Preventiva", b =>
                {
                    b.HasOne("Preventech.Core.Models.Equipamento", "Referente")
                        .WithMany("ManutPreventiva")
                        .HasForeignKey("ReferenteId");

                    b.Navigation("Referente");
                });

            modelBuilder.Entity("Preventech.Core.Models.Equipamento", b =>
                {
                    b.Navigation("ManutPreditiva");

                    b.Navigation("ManutPreventiva");
                });
#pragma warning restore 612, 618
        }
    }
}
